default:
  image: $CI_REGISTRY_IMAGE:latest

cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
    - $PWD/cache/.gradle/

stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=cache/.gradle
  - chmod +x ./gradlew

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

variables:
  GITLAB_ADVANCED_SAST_ENABLED: 'true'

gemnasium-dependency_scanning:
  before_script: []

secret_detection:
  before_script: []

semgrep-sast:
  before_script: []

gitlab-advanced-sast:
  before_script: []

build_base_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/debug:769
    entrypoint: [""]
  # if merging to main and detected changes in Dockerfile
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" 
      when: never # don't run on pipeline triggers
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - docker/Dockerfile
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile"
      --destination $CI_REGISTRY_IMAGE:latest
      --force

lint:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" 
      when: never
    - when: always
  script:
    - ./gradlew lint

build:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" 
      when: never
    - when: always
  script:
    - ./gradlew buildLibrariesRelease
  artifacts:
    paths:
      - api/build/libs/*.jar
      - core/build/outputs/aar/*-release.aar
      - auth/build/outputs/aar/*-release.aar
      - mfa/build/outputs/aar/*-release.aar
    expire_in: 1 hour
