default:
  image: $CI_REGISTRY_IMAGE:latest

cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
    - $PWD/cache/.gradle/

stages:
  - build
  - test
  - publish
  - deploy

before_script:
  - export GRADLE_USER_HOME=cache/.gradle
  - chmod +x ./gradlew

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

.aws-prep: &aws-prep
  - |
    mkdir -p ~/.aws
    echo "${OIDC_TOKEN}" > /tmp/web_identity_token
    echo -e "[profile oidc]\nrole_arn=${ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config

variables:
  GITLAB_ADVANCED_SAST_ENABLED: 'true'

gemnasium-dependency_scanning:
  before_script: []

secret_detection:
  before_script: []

semgrep-sast:
  before_script: []

gitlab-advanced-sast:
  before_script: []

build_base_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/debug:769
    entrypoint: [""]
  # if merging to main and detected changes in Dockerfile
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" 
      when: never # don't run on pipeline triggers
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - docker/Dockerfile
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile"
      --destination $CI_REGISTRY_IMAGE:latest
      --force

lint:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" 
      when: never
    - when: always
  script:
    - ./gradlew lint

build:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" 
      when: never
    - if: $CI_COMMIT_TAG 
      when: never
    - when: always
  script:
    - ./gradlew buildLibrariesRelease
  artifacts:
    paths:
      - api/build/libs/*.jar
      - core/build/outputs/aar/*-release.aar
      - auth/build/outputs/aar/*-release.aar
      - mfa/build/outputs/aar/*-release.aar
    expire_in: 1 hour

create_release:
  stage: publish
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "A release is being created"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_TAG
      when: always
  release:
    tag_name: $CI_COMMIT_TAG
    description: $CI_COMMIT_TAG
    ref: $CI_COMMIT_SHA

build-release:
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^(api|core|auth|mfa)-.+$/'
  script:
    - MODULE="${CI_COMMIT_TAG%%-*}"
    - VERSION="${CI_COMMIT_TAG#*-}"
    - ./gradlew ":$MODULE:assembleRelease -PmoduleVersion=$VERSION"
  artifacts:
    paths:
      - api/build/libs/*.jar
      - core/build/outputs/aar/*-release.aar
      - auth/build/outputs/aar/*-release.aar
      - mfa/build/outputs/aar/*-release.aar
    expire_in: 1 hour

deploy-aws:
  stage: deploy
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  environment: production
  rules:
    - if: '$CI_COMMIT_TAG =~ /^(api|core|auth|mfa)-.+$/'
      when: manual
  id_tokens:
    OIDC_TOKEN:
      aud: https://gitlab.com
  variables:
    S3_BUCKET: $AWS_PRODUCTION_S3_BUCKET
    ROLE_ARN: arn:aws:iam::$AWS_PRODUCTION_ACCOUNT_ID:role/$AWS_PRODUCTION_ROLE_NAME
  before_script:
    - *aws-prep
  script:
    - sh ./scripts/aws-deploy-s3.sh
