package com.loginid.mfa.models

/**
 * Options for performing an MFA (Multi-Factor Authentication) factor.
 *
 * @property session The MFA state session. This should be obtained from a previous MFA request or initiation step.
 * @property payload The payload required for completing the authentication factor. This typically contains user input or challenge-response data.
 * @property autoFill Enables passkey support in browser autofill suggestions (conditional UI), if supported.
 * @property displayName A human-palatable name for the user account, intended only for display on your passkeys.
 * @property txPayload An updated transaction payload generated by the merchant to represent the purchase or operation being confirmed. This updates the initial `txPayload` used in the `beginFlow` method.
 */
data class PerformActionOptions(
    val session: String? = null,
    val payload: String? = null,
    val autoFill: Boolean? = null,
    val displayName: String? = null,
    val txPayload: String? = null
)
